directory: "/node/codeless" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/node/codeless"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm" 
    directory: "/node/sdk" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/node/sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "dotnet-sdk" 
    directory: "/dotnet/codeless" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/dotnet/codeless"
    schedule:
      interval: "weekly"

  - package-ecosystem: "dotnet-sdk" 
    directory: "/dotnet/sdk" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/dotnet/sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" 
    directory: "/go/sdk" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/go/sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven" 
    directory: "/java/agent" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/java/agent"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven" 
    directory: "/java/springbootstarter" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/java/springbootstarter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer" 
    directory: "/php/sdk" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/php/sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer" 
    directory: "/php/codeless" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/php/codeless"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip" 
    directory: "/python/codeless" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/python/codeless"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip" 
    directory: "/python/sdk" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/python/sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/local-aspire"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/local-collector/azure-monitor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/local-collector/datadog"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/local-collector/zipkin"
    schedule:
      interval: "weekly"
